services:
  - type: web
    name: 語学教材作成ツール
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_practical.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false  # セキュアな環境変数として設定
    healthCheckPath: /_stcore/health
